version: "3.9"

name: "codeminer42"

services:
  backend:
    build:
      context: ./apps/backend
    env_file:
      - ./apps/backend/.env
    volumes:
      - ./apps/backend:/backend
    links:
      - postgres
    ports:
      - "3000:3000"

  postgres:
    image: postgres:15.3-bullseye
    env_file:
      - ./apps/backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./temp/postgresql-data:/var/lib/postgresql/data
