# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby File.read(".ruby-version").strip

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.5"
# https://github.com/svenfuchs/rails-i18n#configuration
gem "rails-i18n", "~> 7.0"
# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"
# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"
# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"
# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"
# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  # https://github.com/rweng/pry-rails#usage
  gem "pry-rails", "~> 0.3.9"
  # https://github.com/bkeepers/dotenv#rails
  gem "dotenv-rails", "~> 2.8"
  # https://github.com/rubocop-hq/rubocop-rails#usage
  gem "rubocop-rails", "~> 2.19"
  # https://github.com/rubocop-hq/rubocop-performance#usage
  gem "rubocop-performance", "~> 1.18"
  # https://github.com/rubocop/rubocop-factory_bot#usage
  gem "rubocop-factory_bot", "~> 2.23"
  # https://github.com/backus/rubocop-rspec
  gem "rubocop-rspec", "~> 2.22"
  # https://github.com/rubocop/rubocop-capybara#rubocop-configuration-file
  gem "rubocop-capybara", "~> 2.18"
  # https://github.com/thoughtbot/factory_bot_rails
  gem "factory_bot_rails", "~> 6.2"
  # https://github.com/thoughtbot/shoulda-matchers
  gem "shoulda-matchers", "~> 5.3"
end

group :test do
  # https://github.com/rspec/rspec-rails#installation
  gem "rspec-rails", "~> 6.0"
  # https://github.com/DatabaseCleaner/database_cleaner
  gem "database_cleaner", "~> 2.0"
  # https://github.com/teamcapybara/capybara#setup
  gem "capybara", "~> 3.39"
  # https://github.com/stympy/faker
  gem "faker", "~> 3.2"
end

# https://github.com/joeljunstrom/ruby_luhn#basic-luhn-
gem "luhn", "~> 1.0"
# https://github.com/collectiveidea/interactor-rails#usage
gem "interactor-rails", "~> 2.2"
# https://github.com/rails-api/active_model_serializers/tree/0-10-stable#getting-started
gem "active_model_serializers", "~> 0.10.13"
